### ISSUE TITLE
O is not circular

### ISSUE THREAD

**Issue by tfukaza** [uclaacm/Westwood_Sans#9]
For some reason, the 'O' and 'o' are not symmetrical - it appears to be bulging out to one side.
<img width="651" alt="Screen Shot 2021-03-20 at 10 13 15 PM" src="https://user-images.githubusercontent.com/40327230/111894616-7f2cb400-89c9-11eb-83aa-77c6e27265c6.png">

**Comment by willhsieh** [comment]
Fixed for both regular and bold
